/**
BY SUBMITTING THIS FILE TO CARMEN, I CERTIFY THAT I HAVE PERFORMED ALL OF THE WORK TO CREATE THIS FILE AND/OR
DETERMINE THE ANSWERS FOUND WITHIN THIS FILE MYSELF WITH NO ASSISTANCE FROM ANY PERSON (OTHER THAN THE
INSTRUCTOR OR GRADERS OF THIS COURSE) AND I HAVE STRICTLY ADHERED TO THE TENURES OF THE OHIO STATE
UNIVERSITY’S ACADEMIC INTEGRITY POLICY.
*/

#include <studio.h>

int main() {
	int numbers[] = {1, 2, 3, 4, 5};
	int sum = 0;

	for (int i = 0; i <5; i++) {
		sum = sum + numbers[i];
	}

	printf("Sum: %d\n", sum);

	return 0;
}
